#!/bin/bash

export NGINX_PID_FILE="$OPENSHIFT_KIBANA_DIR/run/nginx.pid"
export NGINX_VERSION=${NGINX_VERSION:-1.7.8}
export NGINX_EXEC="$OPENSHIFT_KIBANA_DIR/nginx/versions/$NGINX_VERSION/bin/nginx"
export NGINX_CONFIG_FILE="$OPENSHIFT_KIBANA_DIR/conf/nginx.conf"
export KIBANA_PID_FILE="$OPENSHIFT_KIBANA_DIR/run/kibana.pid"
export KIBANA_CONFIG_DIR="$OPENSHIFT_REPO_DIR/config/"

function _install_kibana_version()
{
	local VERSION=$1

	if [ -d $OPENSHIFT_KIBANA_DIR/kibana ]; then
		echo Removing old version
		rm -rf $OPENSHIFT_KIBANA_DIR/kibana
	fi

	echo Downloading version $VERSION
	mkdir $OPENSHIFT_KIBANA_DIR/kibana
	curl https://download.elasticsearch.org/kibana/kibana/kibana-$VERSION-linux-x64.tar.gz | tar xzf - --strip-components=1 -C $OPENSHIFT_KIBANA_DIR/kibana
}


function _is_scalable()
{
  if [ "${OPENSHIFT_APP_DNS}" != "${OPENSHIFT_GEAR_DNS}" ]; then
    return 0
  elif [ -n "${OPENSHIFT_HAPROXY_DIR}" ]; then
    return 0
  fi
  return 1
}

function _build_config()
{
  _is_scalable && local S=1 || local S=0

  # Process all ERB templates first
  for FILE in $KIBANA_CONFIG_DIR/*.erb; do
    [ -f "$FILE" ] || continue
    SCALABLE=$S oo-erb "$FILE" > "${FILE%.erb}"
  done
}

